Section "Screen"
    Identifier "Screen0"
    Device     "Card0"
    DefaultDepth 24

	# Allow app to decide the resolution
    SubSection "Display"
        Depth 24
    EndSubSection

    SubSection "Display"
        Depth 16
    EndSubSection
    
    SubSection "Display"
        Depth 8
    EndSubSection
    
EndSection
